esphome:
  name: esp-fumecube
  platformio_options: #https://github.com/esphome/issues/issues/2931
    board_build.flash_mode: dio  

esp32:
  board: esp32-c3-devkitm-1
  framework:
### Arduino
    # type: arduino
    # version: dev
    # platform_version: https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream

### IDF
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Enable signal on GPIO6
power_supply:
    id: relay_pwr
    pin: GPIO6

# PWM output on GPIO7
output:
  - platform: ledc
    id: gpio_pwm
    power_supply: relay_pwr
    pin: GPIO7
    #channel: 0
    frequency: 2000Hz

# LED output status out GPIO3
  - platform: gpio
    id: led_green
    pin: GPIO3
    inverted: true
  

# LED status out GPIO2
light:
  - platform: status_led
    id: led_red
    pin: 
      number: GPIO2
      inverted: true

fan:
  - platform: speed
    output: gpio_pwm
    #speed_count: 4
    name: "FumeCube Speed"
    restore_mode: ALWAYS_OFF
    on_turn_on:
      then:
        - output.turn_on: 
            id: led_green
    on_turn_off:
      then:
        - output.turn_off: 
            id: led_green

